apiVersion: v1
kind: Template
metadata:
  name: mail-sink
objects:

- apiVersion: v1
  kind: ImageStream
  metadata:
    labels:
      app: ${APPLICATION_NAME}
    name: ${APPLICATION_NAME}
  spec:
    tags:
    - annotations:
        description: The Mail Sink Docker image
        tags: ${APPLICATION_NAME}
      from:
        kind: DockerImage
        name: ${APPLICATION_NAME}:latest
      importPolicy: {}
      name: latest

- kind: BuildConfig
  apiVersion: v1
  metadata:
    name: "${APPLICATION_NAME}-docker-build"
    labels:
      app: "${APPLICATION_NAME}"
  spec:
    triggers:
    - type: ImageChange
      imageChange: {}
    - type: ConfigChange
    source:
      type: Git
      git:
        uri: "${SOURCE_REPOSITORY_URL}"
        ref: "${SOURCE_REPOSITORY_REF}"
      contextDir: ${DOCKERFILE_PATH}
    strategy:
      dockerStrategy:
        dockerfilePath: ${DOCKERFILE_NAME}
        env:
          - name: "JENKINS_VERSION"
            value: "${JENKINS_VERSION}"
          - name: "DOCKERFILE_PATH"
            value: "${DOCKERFILE_PATH}"
    output:
      to:
        kind: "ImageStreamTag"
        name: "${APPLICATION_NAME}:latest"
    resources: {}
    postCommit: {}

- apiVersion: v1
  kind: DeploymentConfig
  metadata:
    annotations:
    labels:
      app: ${APPLICATION_NAME}
    name: ${APPLICATION_NAME}
  spec:
    replicas: 1
    selector:
      name: ${APPLICATION_NAME}
    strategy:
      activeDeadlineSeconds: 21600
      recreateParams:
        timeoutSeconds: 600
      resources: {}
      type: Recreate
    template:
      metadata:
        labels:
          name: ${APPLICATION_NAME}
      spec:
        containers:
          image: ' '
          imagePullPolicy: IfNotPresent
          livenessProbe:
            failureThreshold: 30
            httpGet:
              path: /login
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 420
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 3
          name: ${APPLICATION_NAME}
          resources:
            limits:
              memory: ${MEMORY_LIMIT}
          securityContext:
            capabilities: {}
            privileged: false
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
        dnsPolicy: ClusterFirst
        restartPolicy: Always
        schedulerName: default-scheduler
        securityContext: {}
        serviceAccount: jenkins
        serviceAccountName: jenkins
        terminationGracePeriodSeconds: 30
    triggers:
    - imageChangeParams:
        automatic: true
        containerNames:
        - ${APPLICATION_NAME}
        from:
          kind: ImageStreamTag
          name: ${APPLICATION_NAME}:latest
      type: ImageChange
    - type: ConfigChange

- apiVersion: v1
  kind: Service
  metadata:
    labels:
      app: ${APPLICATION_NAME}
    name: mail-sink-web
  spec:
    ports:
    - name: agent
      port: 4443
      protocol: TCP
      targetPort: 4443
    selector:
      name: ${APPLICATION_NAME}
    sessionAffinity: None
    type: ClusterIP

- apiVersion: v1
  kind: Route
  metadata:
    annotations:
    labels:
      app: ${APPLICATION_NAME}
    name: ${APPLICATION_NAME}
  spec:
    tls:
      insecureEdgeTerminationPolicy: Redirect
      termination: edge
    to:
      kind: Service
      name: ${APPLICATION_NAME}
      weight: 100
    wildcardPolicy: None

parameters:
- description: The name for the application.
  name: APPLICATION_NAME
  required: true
  value: mail-sink
- description: Git source URI for application
  name: SOURCE_REPOSITORY_URL
  value: "https://github.com/justindav1s/ocp-appdev.git"
  required: true
- description: Git branch/tag reference
  name: SOURCE_REPOSITORY_REF
  value: "master"
  required: false
- name: DOCKERFILE_PATH
  displayName: Dockerfile path
  description: Path within Git Repo wehere Dockerfile can be found.
  value: "homework/jenkins"
  required: false
- name: DOCKERFILE_NAME
  displayName: Dockerfile name
  description: Name of Dockerfile.
  value: "Dockerfile"
  required: true
- name: MEMORY_LIMIT
  description: Heap for JVM
  value: "1Gi"
